"""initial schema

Revision ID: 46ae41491a29
Revises: 
Create Date: 2026-05-11 21:55:48.485359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ae41491a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('material_type', sa.Enum('raw_material', 'finished_goods', name='materialtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'warehouse', 'production', 'finance', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fg_material_id', sa.Integer(), nullable=False),
    sa.Column('rm_material_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['fg_material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['rm_material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.String(length=20), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', name='prstatus'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pr_number')
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'picking', 'shipped', 'delivered', 'invoiced', 'paid', 'cancelled', name='sostatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_number')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('gr_in', 'wo_consume', 'wo_produce', 'so_ship', 'adjustment', name='transactiontype'), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(length=25), nullable=True),
    sa.Column('qty_change', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_number', sa.String(length=20), nullable=False),
    sa.Column('fg_material_id', sa.Integer(), nullable=False),
    sa.Column('target_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'in_progress', 'production_complete', 'completed', name='wostatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fg_material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wo_number')
    )
    op.create_table('delivery_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('do_number', sa.String(length=20), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'shipped', 'delivered', name='dostatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('do_number')
    )
    op.create_table('fg_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=25), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'shipped', 'consumed', name='fgbatchstatus'), nullable=False),
    sa.Column('produced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=20), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'confirmed', 'received', 'closed', 'cancelled', name='postatus'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requisitions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', name='salesinvoicestatus'), nullable=False),
    sa.Column('journal_entry', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('wo_production_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', name='stagestatus'), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gr_number', sa.String(length=20), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('gross_weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('tare_weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('net_weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('weight_variance_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_within_tolerance', sa.Boolean(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gr_number')
    )
    op.create_table('receipt_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('journal_entry', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_number')
    )
    op.create_table('so_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('qty_picked', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fg_batches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('match_status', sa.Enum('pending', 'matched', 'exception', name='invoicematchstatus'), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('journal_entry', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_number')
    )
    op.create_table('rm_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(length=25), nullable=False),
    sa.Column('gr_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('available', 'locked', 'consumed', 'returned', name='rmlotstatus'), nullable=False),
    sa.Column('putaway_location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gr_id'], ['goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    op.create_table('wo_lot_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('rm_lot_id', sa.Integer(), nullable=False),
    sa.Column('qty_allocated', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qty_consumed', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['rm_lot_id'], ['rm_lots.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wo_lot_allocations')
    op.drop_table('rm_lots')
    op.drop_table('payment_vouchers')
    op.drop_table('supplier_invoices')
    op.drop_table('so_line_items')
    op.drop_table('receipt_vouchers')
    op.drop_table('goods_receipts')
    op.drop_table('wo_production_stages')
    op.drop_table('sales_invoices')
    op.drop_table('purchase_orders')
    op.drop_table('fg_batches')
    op.drop_table('delivery_orders')
    op.drop_table('work_orders')
    op.drop_table('stock_transactions')
    op.drop_table('sales_orders')
    op.drop_table('purchase_requisitions')
    op.drop_table('bom_items')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('materials')
    op.drop_table('customers')
    # ### end Alembic commands ###
